import { test as base, expect } from '../reporting-browser/node_modules/@playwright/test/index.mjs';
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
const qaDir=path.dirname(new URL(import.meta.url).pathname);
const root=path.resolve(qaDir,'../..');
const origin='https://qa.invalid';
const remote='https://bookedradar-platform.onrender.com';
const source=JSON.parse(await fs.readFile(qaDir+'/source-manifest.json','utf8'));
const pages={owner:'owner-brief.html',radar:'radarproof-dashboard.html',signup:'signup.html'};
const defs={owner:{endpoint:'/api/v1/owner-brief',refresh:'#load',money:'#revenue',detail:'#attention',metrics:['newOpp','recovered','revenue','leaks','calls','transfers','gaps','memberships','reviews','risk']},radar:{endpoint:'/api/v1/radarproof',refresh:'#saveToken',money:'#confirmed',detail:'#sources',metrics:['captured','recovered','estimated','confirmed','callsHandled','humanTransfers','spamScreened','callsWithTranscript','knowledgeGaps','rate','pending']}};
function payload(kind,amount=321){const data={newOpportunities:4,opportunitiesCaptured:4,recoveredOpportunities:2,confirmedRevenue:amount,estimatedRecoveredValue:500,estimatedValueAtRisk:600,openRevenueLeaks:1,callsHandled:3,humanTransfers:1,knowledgeGaps:1,membershipRenewalsDue:1,reviewEligibleJobs:1,recoveryRate:.5,pendingActions:1,blockedActions:1,recoveryEvidence:{status:'unavailable'},dataCoverage:{notice:'SYNTHETIC QA: marked tests excluded; unmarked history is unverified; mixed-lineage quarantine may omit genuine activity.'},disclaimer:'SYNTHETIC QA: diagnostic estimates are not confirmed revenue or payment settlement.',callActivity:{callsHandled:3,humanTransfers:1,spamScreened:0,callsWithTranscript:2,knowledgeGaps:1},bySource:{'synthetic-web':{opportunities:4,recovered:2,estimatedValue:500}},topAttentionItems:[{priority:'high',type:'synthetic_follow_up',source:'synthetic-web',ageHours:2,recommendedNextAction:'SYNTHETIC QA follow-up only',estimatedOpportunityValue:600}]};return kind==='owner'?{brief:data}:{report:data};}
const test=base.extend({qa:async({context,page,browser},use,info)=>{
  const audit={title:info.title,commit:source.commit,browser:browser.version(),playwright:JSON.parse(await fs.readFile(qaDir+'/../reporting-browser/node_modules/@playwright/test/package.json','utf8')).version,requests:[],unexpected:[],pageErrors:[],consoleErrors:[],injectedFailures:[],sources:[],screenshots:[],geometry:[]};
  const files={};
  for(const file of source.files){const bytes=await fs.readFile(root+'/'+file.path);expect(crypto.createHash('sha256').update(bytes).digest('hex')).toBe(file.sha256);if(file.path.startsWith('public/'))files['/dashboard/'+file.path.slice(7)]={bytes,file};if(file.path.startsWith('website/src/'))files['/'+file.path.slice(12)]={bytes,file};}
  files['/']=files['/index.html'];
  let apiMode='success',formMode='hold',pending=[];
  const headers={'access-control-allow-origin':origin,'access-control-allow-methods':'GET, POST, OPTIONS','access-control-allow-headers':'content-type,authorization','cache-control':'no-store'};
  page.on('pageerror',e=>audit.pageErrors.push(e.message));
  audit.finished=[];audit.failed=[];page.on('requestfinished',r=>audit.finished.push(r.url()));page.on('requestfailed',r=>audit.failed.push({url:r.url(),error:r.failure()?.errorText}));
  page.on('download',async download=>{audit.unexpected.push('DOWNLOAD '+download.url());await download.cancel();});
  context.on('page',async popup=>{audit.unexpected.push('POPUP '+popup.url());await popup.close();});
  page.on('console',m=>{if(m.type()==='error')audit.consoleErrors.push({text:m.text(),url:m.location().url});});
  await context.route('**/*',async route=>{
    const req=route.request(),url=new URL(req.url()),method=req.method();
    audit.requests.push({url:req.url(),method,resourceType:req.resourceType()});
    const file=files[url.pathname];
    if(url.origin===origin&&method==='GET'&&file){audit.sources.push(file.file.path);await route.fulfill({status:200,contentType:url.pathname.endsWith('.js')?'text/javascript':url.pathname.endsWith('.css')?'text/css':'text/html',body:file.bytes,headers});return;}
    if(url.origin===origin&&url.pathname==='/favicon.ico'&&method==='GET'){await route.fulfill({status:204});return;}
    const isTelemetry=url.origin===remote&&['/api/v1/telemetry/events','/api/v1/public/growth-event'].includes(url.pathname);
    const isForm=[origin,remote].includes(url.origin)&&url.pathname==='/api/v1/public/proof-pilot';
    if((isTelemetry||isForm)&&method==='OPTIONS'){await route.fulfill({status:204,headers});return;}
    if(isTelemetry&&method==='POST'){const body=JSON.parse(req.postData());expect(body).not.toHaveProperty('email');expect(body).not.toHaveProperty('name');await route.fulfill({status:200,headers,json:{ok:true}});return;}
    if(isForm&&method==='POST'){const body=JSON.parse(req.postData());expect(body.email).toBe('qa-mobile@example.invalid');expect(body.business).toBe('SYNTHETIC QA BUSINESS');pending.push({route,body});if(formMode!=='hold')await respondForm(pending.at(-1),formMode);return;}
    const kind=Object.keys(defs).find(k=>defs[k].endpoint===url.pathname);
    if(url.origin===origin&&kind&&method==='GET'&&url.searchParams.get('tenant')==='qa-a'&&req.headers().authorization==='Bearer qa-token-a'){
      if(apiMode==='network'){audit.injectedFailures.push({url:req.url(),mode:apiMode});await route.abort('failed');return;}
      if(apiMode==='http'){audit.injectedFailures.push({url:req.url(),mode:apiMode});await route.fulfill({status:503,headers,json:{error:'synthetic_failure'}});return;}
      if(apiMode==='json'){await route.fulfill({status:200,headers,contentType:'application/json',body:'{ invalid synthetic JSON'});return;}
      await route.fulfill({status:200,headers,json:payload(kind,apiMode==='recovery'?222:321)});return;
    }
    audit.unexpected.push(method+' '+req.url());await route.abort('blockedbyclient');
  });
  await context.routeWebSocket('**/*',ws=>{audit.unexpected.push('WS '+ws.url());ws.close();});
  await context.addInitScript(()=>{sessionStorage.setItem('br_tenant','qa-a');sessionStorage.setItem('br_admin_token','qa-token-a');});
  async function respondForm(item,mode){if(mode==='network'){audit.injectedFailures.push({url:item.route.request().url(),mode});await item.route.abort('failed');}else if(mode==='http'){audit.injectedFailures.push({url:item.route.request().url(),mode});await item.route.fulfill({status:503,headers,json:{ok:false}});}else if(mode==='json')await item.route.fulfill({status:200,headers,contentType:'application/json',body:'{ invalid synthetic JSON'});else await item.route.fulfill({status:200,headers,json:{ok:true,duplicate:mode==='duplicate'}});}
  const qa={page,audit,pending,api(mode){apiMode=mode;},form(mode){formMode=mode;},respondForm,
    async open(kind,width){await page.setViewportSize({width,height:844});await page.goto(origin+(pages[kind]?'/dashboard/'+pages[kind]+'?tenant=qa-a':kind==='home'?'/':'/audit.html'),{waitUntil:'domcontentloaded',timeout:10000});if(kind==='audit')await expect(page.locator('#brAuditLeadForm')).toBeVisible();if(kind==='signup')await expect(page.locator('#pilot-request')).toBeVisible();},
    async screenshot(name){const file=info.outputPath(name+'.png');await page.screenshot({path:file,fullPage:true});audit.screenshots.push({name,path:file});for(const selector of ['#brAuditLead','.resultBlock','#pilot'])if(await page.locator(selector).count()&&await page.locator(selector).isVisible()){const part=info.outputPath(name+'-'+selector.replace(/[^a-zA-Z]/g,'')+'.png');await page.locator(selector).screenshot({path:part});audit.screenshots.push({name:name+' '+selector,path:part});}},
    async geometry(label){const result=await page.evaluate(()=>{const issues=[],w=innerWidth;const visible=el=>!!(el.offsetWidth||el.offsetHeight||el.getClientRects().length)&&getComputedStyle(el).visibility!=='hidden'&&!el.closest('[aria-hidden="true"]');if(document.documentElement.scrollWidth>w+1)issues.push('document horizontal overflow');for(const el of document.querySelectorAll('input,select,textarea,button,a,nav,header,h1,h2,h3,fieldset,.card,.question,.option,#brAuditLead,.resultBlock,.success,#coverage,#status,#brAuditStatus,.source,.item')){if(!visible(el)||el.classList.contains('hp'))continue;const r=el.getBoundingClientRect();if(r.left<-1||r.right>w+1)issues.push('outside viewport: '+(el.id||el.className||el.tagName));if(el.scrollWidth>el.clientWidth+2&&!['INPUT','SELECT','TEXTAREA'].includes(el.tagName))issues.push('content overflow: '+(el.id||el.className||el.tagName));}return{width:w,client:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth,issues};});audit.geometry.push({label,...result});return result;},
    async cleared(kind){for(const id of defs[kind].metrics)await expect(page.locator('#'+id)).toHaveText('Unavailable');await expect(page.locator('#coverage')).toHaveText('Data unavailable; synthetic marker coverage has not been verified.');await expect(page.locator(defs[kind].detail)).not.toContainText('synthetic-web');if(kind==='owner')await expect(page.locator('#recoveryNote')).toBeEmpty();else{await expect(page.locator('#blocked')).toBeEmpty();await expect(page.locator('#disclaimer')).toHaveText('RadarProof data is unavailable.');}}
  };
  try{await use(qa);}finally{audit.viewport=page.viewportSize();if(info.status!==info.expectedStatus&&!page.isClosed())await qa.screenshot('failure');await fs.writeFile(info.outputPath('network-source-evidence.json'),JSON.stringify(audit,null,2));console.log('MOBILE_QA_EVIDENCE',JSON.stringify(audit));await context.close();expect(audit.unexpected).toEqual([]);expect(audit.pageErrors).toEqual([]);const unexpectedConsole=audit.consoleErrors.filter(e=>!audit.injectedFailures.some(f=>e.url===f.url&&e.text===(f.mode==='network'?'Failed to load resource: net::ERR_FAILED':'Failed to load resource: the server responded with a status of 503 (Service Unavailable)')));expect(unexpectedConsole).toEqual([]);}
}});

for(const width of [320,375,390]){
  test('homepage layout and signup path '+width,async({qa})=>{await qa.open('home',width);await qa.screenshot('home-'+width);expect((await qa.geometry('home')).issues).toEqual([]);const link=qa.page.locator('a[href="https://bookedradar-platform.onrender.com/dashboard/signup.html"]');expect(await link.count()).toBeGreaterThan(0);await expect(link.first()).toBeVisible();});
  for(const kind of ['owner','radar'])for(const mode of ['http','network','json'])test(kind+' '+mode+' failure and recovery '+width,async({qa})=>{await qa.open(kind,width);await expect(qa.page.locator('#status')).toHaveText('Live');await expect(qa.page.locator(defs[kind].money)).toHaveText('$321');qa.api(mode);await qa.page.locator(defs[kind].refresh).click();await expect(qa.page.locator('#status')).toHaveText(kind==='owner'?'Unavailable':'Data unavailable');await qa.cleared(kind);await qa.screenshot(kind+'-'+mode+'-'+width);expect((await qa.geometry(mode+' failure')).issues).toEqual([]);qa.api('recovery');await qa.page.locator(defs[kind].refresh).click();await expect(qa.page.locator('#status')).toHaveText('Live');await expect(qa.page.locator(defs[kind].money)).toHaveText('$222');await qa.screenshot(kind+'-recovered-'+mode+'-'+width);expect((await qa.geometry('recovery')).issues).toEqual([]);});
  for(const kind of ['signup','audit']){
    test(kind+' mobile controls and validation '+width,async({qa})=>{await qa.open(kind,width);const p=qa.page;await qa.screenshot(kind+'-ready-'+width);expect((await qa.geometry('ready')).issues).toEqual([]);const pref=p.locator(kind==='signup'?'#contact-preference':'#audit-contact-preference'),phone=p.locator(kind==='signup'?'#phone':'#audit-phone-field input');await expect(pref).toHaveValue('email');await expect(phone).toBeHidden();await expect(phone).toBeDisabled();await pref.selectOption('phone');await expect(phone).toBeVisible();await expect(phone).toHaveAttribute('required','');await expect(phone).toBeEnabled();await qa.screenshot(kind+'-phone-'+width);expect((await qa.geometry('phone')).issues).toEqual([]);await pref.selectOption('email');await expect(phone).toBeHidden();await expect(phone).toBeDisabled();if(kind==='signup'){await p.locator('summary').focus();await p.keyboard.press('Enter');await expect(p.locator('[name=serviceArea]')).toBeVisible();await qa.screenshot(kind+'-optional-'+width);expect((await qa.geometry('optional')).issues).toEqual([]);}else{const first=p.locator('[name=q0]').first();await first.focus();await p.keyboard.press('ArrowRight');await expect(p.locator('[name=q0]').nth(1)).toBeChecked();for(let i=0;i<7;i++)await p.locator('[name=q'+i+']').last().check();await expect(p.locator('#score')).toHaveText('100');await p.locator('#leads').fill('20');await p.locator('#job').fill('100');await p.locator('#rate').fill('10');await expect(p.locator('#money')).toHaveText('$866');await qa.screenshot(kind+'-completed-'+width);expect((await qa.geometry('completed')).issues).toEqual([]);}await p.locator(kind==='signup'?'#submit-request':'#brAuditLeadForm button').click();expect(qa.pending.length).toBe(0);const invalid=await p.evaluate(()=>document.activeElement?.validity?.valid);expect(invalid).toBe(false);});
    for(const mode of ['http','network','json'])test(kind+' '+mode+' failure preserves answers and recovers '+width,async({qa})=>{await qa.open(kind,width);const p=qa.page,form=p.locator(kind==='signup'?'#pilot-request':'#brAuditLeadForm');await form.locator('[name="'+(kind==='signup'?'name':'first')+'"]').fill('SYNTHETIC QA');await form.locator('[name="'+(kind==='signup'?'business':'company')+'"]').fill('SYNTHETIC QA BUSINESS');await form.locator('[name=email]').fill('qa-mobile@example.invalid');if(kind==='audit')for(let i=0;i<7;i++)await p.locator('[name=q'+i+']').last().check();const button=form.locator('button');await button.click({clickCount:2});await expect.poll(()=>qa.pending.length).toBe(1);await expect(button).toBeDisabled();await qa.screenshot(kind+'-pending-'+mode+'-'+width);expect(qa.pending.length).toBe(1);await qa.respondForm(qa.pending[0],mode);const status=p.locator(kind==='signup'?'#status':'#brAuditStatus');await expect(status).toContainText('couldn’t confirm');await expect(status).toContainText('don’t submit repeatedly');await expect(form.locator('[name=email]')).toHaveValue('qa-mobile@example.invalid');await expect(button).toBeEnabled();await qa.screenshot(kind+'-'+mode+'-failure-'+width);expect((await qa.geometry(mode+' failure')).issues).toEqual([]);qa.form('success');await button.click();await expect.poll(()=>qa.pending.length).toBe(2);if(kind==='signup'){await expect(p.locator('#success')).toBeVisible();await expect(p.locator('#confirmation')).toContainText('email only');await expect(p.locator('#success')).toBeFocused();}else{await expect(status).toContainText('with no sales call');await expect(button).toBeDisabled();}expect(qa.pending[1].body).not.toHaveProperty('phone');await qa.screenshot(kind+'-success-'+mode+'-'+width);expect((await qa.geometry('success')).issues).toEqual([]);});
    test(kind+' duplicate notice '+width,async({qa})=>{await qa.open(kind,width);const p=qa.page,form=p.locator(kind==='signup'?'#pilot-request':'#brAuditLeadForm');await form.locator('[name="'+(kind==='signup'?'name':'first')+'"]').fill('SYNTHETIC QA');await form.locator('[name="'+(kind==='signup'?'business':'company')+'"]').fill('SYNTHETIC QA BUSINESS');await form.locator('[name=email]').fill('qa-mobile@example.invalid');if(kind==='audit')for(let i=0;i<7;i++)await p.locator('[name=q'+i+']').last().check();qa.form('duplicate');await form.locator('button').click();await expect(p.locator(kind==='signup'?'#confirmation':'#brAuditStatus')).toContainText('already');await qa.screenshot(kind+'-duplicate-'+width);expect((await qa.geometry('duplicate')).issues).toEqual([]);});
  }
}
